# Generated by Django 5.0.7 on 2024-07-18 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_user_usersactivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersactivity',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UsersActivity',
        ),
    ]
