# Generated by Django 5.0.7 on 2024-08-03 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_remove_usersactivity_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
    ]
